env:
  es2022: true
  mocha: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  space-before-function-paren:
    - 'error'
    - anonymous: always
      asyncArrow: always
      named: never
